name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      avalanchegoRepo:
        description: 'qmallgo github repository'
        required: true
        default: 'dim4egster/qmallgo'
      avalanchegoBranch:
        description: 'qmallgo branch'
        required: true
        default: 'master'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: check out ${{ github.event.inputs.avalanchegoRepo }} ${{ github.event.inputs.avalanchegoBranch }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.avalanchegoRepo }}
          ref: ${{ github.event.inputs.avalanchegoBranch }}
          path: qmallgo
          token: ${{ secrets.AVALANCHE_PAT }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: change qmallgo dep
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          go mod edit -replace github.com/dim4egster/qmallgo=./qmallgo
          go mod tidy
          go clean -modcache # avoid conflicts with the golangci-lint-action cache
      - run: ./scripts/lint_allowed_geth_imports.sh
        shell: bash
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.47
          working-directory: .
          args: --timeout 3m
  test:
    name: Golang Unit Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.18']
        os: [macos-11.0, ubuntu-18.04, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: check out ${{ github.event.inputs.avalanchegoRepo }} ${{ github.event.inputs.avalanchegoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.avalanchegoRepo }}
        ref: ${{ github.event.inputs.avalanchegoBranch }}
        path: qmallgo
        token: ${{ secrets.AVALANCHE_PAT }}
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: change qmallgo dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/dim4egster/qmallgo=./qmallgo
        go mod tidy
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh
      shell: bash
    - run: ./scripts/coverage.sh
      shell: bash
  test-race:
    name: Golang Unit Tests Race Detection v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ['1.18']
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: check out ${{ github.event.inputs.avalanchegoRepo }} ${{ github.event.inputs.avalanchegoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.avalanchegoRepo }}
        ref: ${{ github.event.inputs.avalanchegoBranch }}
        path: qmallgo
        token: ${{ secrets.AVALANCHE_PAT }}
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: change qmallgo dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/dim4egster/qmallgo=./qmallgo
        go mod tidy
    - run: go mod download
      shell: bash
    - run: ./scripts/build.sh evm
      shell: bash
    - run: ./scripts/build_test.sh -race
      shell: bash
  e2e:
    name: Golang E2E Tests v${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.18' ]
        os: [ ubuntu-20.04 ]
    steps:
    - uses: actions/checkout@v2
    - name: check out ${{ github.event.inputs.avalanchegoRepo }} ${{ github.event.inputs.avalanchegoBranch }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.avalanchegoRepo }}
        ref: ${{ github.event.inputs.avalanchegoBranch }}
        path: qmallgo
        token: ${{ secrets.AVALANCHE_PAT }}
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: change qmallgo dep
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        go mod edit -replace github.com/dim4egster/qmallgo=./qmallgo
        go mod tidy
    - name: prepare qmallgo directory for docker copy
      if: ${{ github.event_name == 'workflow_dispatch' }}
      # mv qmallgo/ to nested dir qmallgo/qmallgo/
      # required because docker instruction "COPY dir ." copies dir/* to .
      run: mkdir avalanchego_tmp && mv qmallgo avalanchego_tmp && mv avalanchego_tmp qmallgo
    #temporary commented while not set KURTOSIS_CLIENT_ID and KURTOSIS_CLIENT_SECRET credentials in github secrets
    #- run: .github/workflows/run_e2e_tests.sh --parallelism 1 --client-id $KURTOSIS_CLIENT_ID --client-secret $KURTOSIS_CLIENT_SECRET
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        KURTOSIS_CLIENT_ID: ${{ secrets.KURTOSIS_CLIENT_ID }}
        KURTOSIS_CLIENT_SECRET: ${{ secrets.KURTOSIS_CLIENT_SECRET }}
